// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_DENV_long_decay_titres_cpp
NumericMatrix simulate_DENV_long_decay_titres_cpp(List inf_times_list, NumericVector decay_rate_vec, double log_first_peak, double phi, double beta, int final_age);
RcppExport SEXP _flavipack_simulate_DENV_long_decay_titres_cpp(SEXP inf_times_listSEXP, SEXP decay_rate_vecSEXP, SEXP log_first_peakSEXP, SEXP phiSEXP, SEXP betaSEXP, SEXP final_ageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type inf_times_list(inf_times_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type decay_rate_vec(decay_rate_vecSEXP);
    Rcpp::traits::input_parameter< double >::type log_first_peak(log_first_peakSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type final_age(final_ageSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_DENV_long_decay_titres_cpp(inf_times_list, decay_rate_vec, log_first_peak, phi, beta, final_age));
    return rcpp_result_gen;
END_RCPP
}
// truncate_at_zero
void truncate_at_zero(NumericMatrix& x);
RcppExport SEXP _flavipack_truncate_at_zero(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    truncate_at_zero(x);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flavipack_simulate_DENV_long_decay_titres_cpp", (DL_FUNC) &_flavipack_simulate_DENV_long_decay_titres_cpp, 6},
    {"_flavipack_truncate_at_zero", (DL_FUNC) &_flavipack_truncate_at_zero, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_flavipack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
